spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smProject?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${dbUser}
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9200

